### ISSUE TITLE
Adjust reviewers/maintainers on gardenlinux-ccloud

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux-ccloud#16]
- [x] Create [Garden Linux Converged Cloud Maintainers](https://github.com/orgs/gardenlinux/teams/garden-linux-converged-cloud-maintainers) group.

- [x] Add the people expected to act as maintainers
   - [x] @fwiesel
   - [x] @toanju 
   - [x] @notandy
   - [x] @BzzyBriel
   - [x] @mchristianl
   - [x] @NotTheEvilOne
   - [x] @defo89

- [x] Assign [Garden Linux Converged Cloud Maintainers](https://github.com/orgs/gardenlinux/teams/garden-linux-converged-cloud-maintainers) as maintainer for [gardenlinux-ccloud](https://github.com/gardenlinux/gardenlinux-ccloud)

**Comment by pnpavlov** [comment]
@toanju , can you please confirm task is completed - if not, please text me to adjust

**Comment by toanju** [comment]
lgtm

**Comment by pnpavlov** [comment]
done
