### ISSUE TITLE
Sort the features and their inclusion to our needs

### ISSUE THREAD

**Issue by toanju** [gardenlinux/gardenlinux-ccloud#17]
**What would you like to be added**:

There are a few items that can be sorted into the respective feature. Respectively we need to check if we need all the current features or if we can reduce the current feature implementations.

**Why is this needed**:

**Comment by NotTheEvilOne** [comment]
Based on #14 I would like to emphasis that the following packages are checked both if they are really needed at all and for which feature they best fit:
- containerd
- curl
- docker.io
- ethtool
- jq
- nfs-common
- open-vm-tools
- socat
- vim

**Comment by toanju** [comment]
After discussion with @defo89 we can remove the features: https://github.com/gardenlinux/gardenlinux-ccloud/pull/18
